### ISSUE TITLE
wrong variable value

### ISSUE THREAD

**Issue by AmeenAli** [idansc/simple-avsd#3]
https://github.com/idansc/simple-avsd/blob/c89f802b5ac2afb81d58c56eb4a5b642a6a48527/code/mmseq2seq_model.py#L46

shouldn't size_flag=False be set to True instead?
Because you already passed a size list to Atten, and inside the constructor, there is a code for initializing an empty size list in case size_flag is set to false, but you already passed a size list and thus no need to init a new size list with Nones
https://github.com/idansc/simple-avsd/blob/c89f802b5ac2afb81d58c56eb4a5b642a6a48527/code/atten.py#L101

**Comment by idansc** [comment]
You are right, the sizes passed are leftovers from different setup, therefore sizes shouldn't be passed with the attention c'tor. 
Just to clarify, passing sizes allows reduction of pairwise potentials using weights, used in [Factor Graph Attention](https://arxiv.org/abs/1904.05880) paper.

**Comment by AmeenAli** [comment]
Thanks,
out of curiosity, can you elaborate more about size_force and self_flag variables?

**Comment by idansc** [comment]
Yes, to derive the pairwise potentials (i.e., cross-data evidence), we reduce an affinity matrix. In factor graph attention paper, using a batch-norm and weighted summation on rows/columns improved the performance. Since the size (e.g., sentence-length, image-roi, video-frames) can be dynamic, I added an option to force size with adaptive pooling. For simple-avsd, reducing the affinity matrix with mean  w/o any additional weights seemed to work, so I remove the need of size altogether. 

- **size_force** use adaptive pooling to force a size on input

- **size_flag** is redundant, basically just a flag indicates if we care about sizes.
